name: Deploy Docker HUB

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_docker_hub:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3.11.1
    
    - name: Docker login
      uses: docker/login-action@v3.6.0
      with:
        username: ${{ secrets.USERNAME_DOCKER_HUB }}
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
    
    - name: Build and push docker image
      uses: docker/build-push-action@v6.18.0
      with: 
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.USERNAME_DOCKER_HUB }}/hotel_api:${{ github.ref_name }}